name: Fetch Issue Timeline

on: watch

jobs:
  build:
    if: github.actor == 'francisfuzz'

    runs-on: ubuntu-latest

    steps:

    - name: Fetch Issue Timeline
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -v -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.mockingbird-preview" "https://api.github.com/repos/actions-packages-examples/issue-timeline/issues/1/timeline"
